name: Automated Games

on:
  schedule:
    # GitHub cron uses UTC

    # SCRAMBLER (Wednesday 07:00 AM → Wednesday 05:30 PM)
    # Run hourly at :00 from 8:00 AM → 5:00 PM ET, plus a final run at 5:30 PM ET.
    - cron: '0 12-21 * * 3'
    - cron: '30 21 * * 3'

    # RIDDLER (Thursday 12:00 PM → Tuesday 05:30 PM)
    # Run once per day at 12:00 PM ET on Fri, Sat, Sun, Mon, Tue,
    # plus a final run at 5:30 PM ET on Tuesday.
    - cron: '0 16 * * 5,6,0,1,2'
    - cron: '30 21 * * 2'

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore OAuth token
        run: |
          mkdir -p config
          cat > config/token.json <<'JSON'
          ${{ secrets.TOKEN_JSON }}
          JSON
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Games Automation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          RIDDLE_LABEL_ID: ${{ secrets.RIDDLE_LABEL_ID }}
          SCRAMBLER_LABEL_ID: ${{ secrets.SCRAMBLER_LABEL_ID }}
        run: |
          source .venv/bin/activate
          python3 src/main.py
